import Head from 'next/head'
import foto from '../public/certificado 2.JPG'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="v-screen h-screen flex flex-row items-start bg-slate-100">
      <div className="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div className="sm:text-center lg:text-left flex flex-col ml-2">
          <Head>
          <title>Guilherme Carvalho</title>
          <meta name="description" content="Generated by create next app" />
          </Head>
          <h1 className="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span className="block xl:inline">Esse sou eu</span>
            <br />
            <span className="block text-indigo-600 xl:inline">Guilherme Carvalho</span>
          </h1>
          <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Apaixonado por Tecnologia e desenvolvimento a tempos, busquei me especializar e aprender cada vez mais. Estudo Desenvolvimento Web na Trybe, uma escola que vai do conhecimento técnico em programação ao aprender a trabalhar e desenvolver capacidades socioemocionais. Trabalho e acredito em projetos que possam gerar uma virada de chave positiva na vida das pessoas.</p>
          <div className="flex w-fit gap-2 items-center justify-around">
            <Link href="/repositorios">
              <button type="button" className="btn btn-outline-primary text-indigo-600">Repositório</button>
            </Link>
            <Link href="/contatos">
              <button type="button" className="btn btn-outline-secondary text-indigo-600">Contato</button>
            </Link>
          </div>
        </div>
      </div>
      <div className="self-stretch mr-20 mt-20" style={{width: "50rem"}}>
        <Image src={foto} alt="minha foto" />
      </div>
    </div>
  )
}
