import Head from 'next/head'
import foto from '../public/certificado 2.JPG'
import styles from '../styles/image.module.css'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="v-screen h-screen flex flex-row items-start bg-slate-100">
      <div className="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div className="sm:text-center lg:text-left flex flex-col gap-1">
          <Head>
          <title>Guilherme Carvalho</title>
          <meta name="description" content="Generated by create next app" />
          </Head>
          <h1 className="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span className="block xl:inline">Esse sou eu</span>
            <br />
            <span className="block text-indigo-600 xl:inline">Guilherme Carvalho</span>
          </h1>
          <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Apaixonado por Tecnologia e desenvolvimento a tempos, busquei me especializar e aprender cada vez mais. Estudo Desenvolvimento Web na Trybe, uma escola que vai do conhecimento técnico em programação ao aprender a trabalhar e desenvolver capacidades socioemocionais. Trabalho e acredito em projetos que possam gerar uma virada de chave positiva na vida das pessoas.</p>
        </div>
      </div>
      <div className="w-1/2 h-1/2 my-8 mx-8 rounded-sm bg-orange-700">
        <Image src={foto} alt="minha foto" />
        {/* vou deixar assim por enquanto dificuldade em estilizar a tag image */}
      </div>
    </div>
  )
}
