/* eslint-disable @next/next/no-img-element */
// eslint-disable-next-line @next/next/no-img-element
import Head from 'next/head'
import Link from 'next/link'

export default function Homedois() {
  return (
    <div className="vh-100 d-flex bg-slate-100">
      <div className="mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div className="sm:text-center lg:text-left d-flex flex-column">
          <Head>
          <title>Guilherme Carvalho</title>
          <meta name="description" content="Generated by create next app" />
          </Head>
          <div className="tracking-tight fw-bolder text-gray-900 sm:text-5xl md:text-6xl">
            <span className="d-block xl:inline mb-2">Esse sou eu</span>
            <span className="d-block text-indigo-600 xl:inline">Guilherme Carvalho</span>
          </div>
          <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Apaixonado por Tecnologia e desenvolvimento a tempos, busquei me especializar e aprender cada vez mais. Estudo Desenvolvimento Web na Trybe, uma escola que vai do conhecimento técnico em programação ao aprender a trabalhar e desenvolver capacidades socioemocionais. Trabalho e acredito em projetos que possam gerar uma virada de chave positiva na vida das pessoas.</p>
          <div className="d-flex gap-2">
            <Link href="/repositorios">
              <a type="button" className="btn btn-outline-primary">Repositório</a>
            </Link>
            <Link href="/contatos">
              <a type="button" className="btn btn-outline-secondary">Contato</a>
            </Link>
          </div>
        </div>
      </div>
      <div className="self-stretch mr-20 mt-20">
        <img src="certificado.JPG" alt="minha foto" style={{width: "50rem"}} className="rounded" />
      </div>
    </div>
  )
}
